Repository nextcloud/talk-desktop, pull requests merged in 2023-06, with the labels that each got.

#210 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
Labels: 3. to review, dependencies, automated

#232 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#235 chore(ci): add dependabot approve merge
  .github/workflows/dependabot-approve-merge.yml
Labels: technical debt

#238 fix(authentication): Use content size on login web-view to avoid scroll on Windows
  src/authentication/login.window.js
Labels: bug, regression, os: Windows 🪟

#240 fix(patchers): fix patching modules resolving by require.resolve
  src/patchers/@nextcloud/auth.js
  src/patchers/@nextcloud/axios.js
  src/patchers/@nextcloud/initial-state.js
  src/patchers/@nextcloud/notify_push.js
  src/patchers/@nextcloud/router.js
  src/patchers/globals.js
  webpack.renderer.config.js
Labels: bug, 4. to release

#247 fix: re-fetch appData on talk hash invalidate
  .eslintrc.js
  forge.config.js
  src/app/AppData.js
  src/app/appData.service.js
  src/app/applyContextMenu.js
  src/authentication/renderer/AuthenticationApp.vue
  src/global.d.ts
  src/main.js
  src/preload.js
  src/talk/renderer/init.js
  src/welcome/welcome.js
  src/welcome/welcome.window.js
Labels: bug, 3. to review

#248 release: v0.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: technical debt
