Repository nextcloud/talk-desktop, pull requests merged in 2023-04, with the labels that each got.

#106 New release notification
  package-lock.json
  package.json
  src/app/githubReleaseNotification.service.js
  src/main.js
Labels: enhancement, 3. to review

#121 Add native context menu
  src/app/applyContextMenu.js
  src/app/applyDownloadNotification.js
  src/authentication/authentication.window.js
  src/authentication/login.window.js
  src/talk/talk.window.js
Labels: bug, enhancement, 3. to review

#125 Fix GitHub Rate Limit error: do not make unnecessary the latest new version requests
  src/app/githubReleaseNotification.service.js
  src/main.js
Labels: bug, 3. to review

#139 Update vulnerable dependencies
  package-lock.json
Labels: security

#141 Fix session loosing caused by different `set-cookie` casing
  src/app/webRequestInterceptor.js
Labels: bug, 3. to review

#142 fix(patchers): fix importing images and sounds using `@nextcloud/router`
  sounds/LibremPhoneCall.ogg
  sounds/join_call.ogg
  sounds/leave_call.ogg
  src/patchers/nextcloud-router.js
Labels: bug, 3. to review
