Repository nextcloud/talk-desktop, pull requests merged in 2023-09, with the labels that each got.

#348 fix: restore app from system tray on reopen
  src/main.js
Labels: bug

#347 Fix: catch http errors on development and styles loading
  src/app/appData.service.js
  src/app/webRequestInterceptor.js
  src/talk/renderer/init.js
Labels: bug, 3. to review

#349 Add release scripts
  README.md
  package-lock.json
  package.json
  scripts/prepare-release-packages.mjs
Labels: 3. to review, technical debt

#354 Release v0.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
