Repository nextcloud/talk-desktop, pull requests merged in 2023-12, with the labels that each got.

#450 fix(i18n): Triple to to ellipsis
  src/authentication/renderer/AuthenticationApp.vue
Labels: bug, 2. developing

#451 release: v0.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#456 release: v0.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#458 fix(authentication): system lang separator
  src/main.js
  src/shared/setupWebPage.js
Labels: bug, 3. to review
