Repository nextcloud/talk-desktop, pull requests merged in 2023-03, with the labels that each got.

#69 chore: Add PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: 3. to review

#72 Fix wrong display-name property from provisioning getUser response
  src/patchers/nextcloud-auth.js
Labels: bug, 3. to review

#76 Fix loosing authentication on notify_push on any ws error
  src/patchers/nextcloud-notify_push.js
  src/talk/renderer/notifications/notifications.store.js
Labels: bug

#77 Add CommandOrControl + Plus hotkey for zoomIn without SHIFT
  src/app/app.menu.js
  src/app/applyWheelZoom.js
  src/talk/talk.window.js
Labels: bug

#88 Fix missed notifications event bus emitting and notification request caching
  src/app/webRequestInterceptor.js
  src/talk/renderer/notifications/notifications.store.js
Labels: bug, 3. to review

#103 Fix unclosable About window on Mac - make About window closable by Escape and a new close button
  src/help/help.window.js
  src/help/renderer/HelpApp.vue
Labels: 3. to review

#105 fix(l10n): 🔣 Set up translations
  .l10nignore
  .tx/backport
  .tx/config
  l10n/.gitkeep
  src/talk/renderer/components/UserMenu.vue
  src/talk/renderer/desktop.app.js
  src/talk/renderer/init.js
Labels: bug, 3. to review

#107 fix(l10n): Add fake info.xml so the translationtool can convert back …
  appinfo/info.xml
Labels: bug, 3. to review

#109 Set up lint-eslint.yml github action
  .github/workflows/lint-eslint.yml
Labels: 3. to review, standardisation, technical debt
