Repository nextcloud/talk-desktop, pull requests merged in 2024-09, with the labels that each got.

#783 fix(viewer): improve styling and loading/error handling
  package-lock.json
  package.json
  src/talk/renderer/Viewer/Viewer.js
  src/talk/renderer/Viewer/ViewerApp.vue
  src/talk/renderer/Viewer/ViewerHandlerBase.vue
  src/talk/renderer/Viewer/ViewerHandlerImages.vue
  src/talk/renderer/Viewer/ViewerHandlerMedia.vue
  src/talk/renderer/Viewer/ViewerHandlerVideos.vue
  src/talk/renderer/Viewer/viewer.utils.ts
  src/talk/renderer/talk.main.js
Labels: bug, 3. to review

#785 feat(viewer): add Text, Markdown and Source Code viewer (read-only)
  src/talk/renderer/Viewer/Viewer.js
  src/talk/renderer/Viewer/ViewerHandlerText.vue
Labels: enhancement, 3. to review

#786 release: v0.37.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#787 refactor: rename mdi components from `Mdi*` to `Icon*`
  src/authentication/renderer/AuthenticationApp.vue
  src/help/renderer/HelpApp.vue
  src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue
  src/talk/renderer/Viewer/ViewerApp.vue
  src/talk/renderer/components/DesktopMediaSourceDialog.vue
  src/talk/renderer/components/DesktopMediaSourcePreview.vue
  src/talk/renderer/components/MainMenu.vue
  src/talk/renderer/components/UserMenu.vue
  src/upgrade/renderer/UpgradeApp.vue
Labels: 3. to review, technical debt

#755 chore: ts support
  .eslintrc.js
  .github/workflows/lint-typescript.yml
  jsconfig.json
  package-lock.json
  package.json
  src/global.d.ts
  src/shared/globals/OC/OcDialogsAdapter.vue
  src/talk/renderer/Viewer/ViewerApp.vue
  src/talk/renderer/Viewer/viewer.service.ts
  tsconfig.json
Labels: 3. to review, technical debt

#799 fix(state): get typing privacy from capabilities
  src/shared/setupWebPage.js
Labels: bug, 3. to review

#800 release: v0.38.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt
