Repository nextcloud/talk-desktop, pull requests merged in 2024-08, with the labels that each got.

#735 fix: disable custom title bar on Linux
  src/authentication/authentication.window.js
  src/talk/talk.window.js
  src/welcome/welcome.window.js
Labels: bug, 3. to review

#736 fix(talk): increase overrides styles specificity
  src/talk/renderer/assets/overrides.css
Labels: bug, 3. to review

#738 fix: make title bar height configurable and adjust to new design
  src/authentication/authentication.window.js
  src/constants.js
  src/talk/renderer/DesktopHeader.vue
  src/talk/renderer/assets/overrides.css
  src/talk/renderer/components/UserMenu.vue
  src/talk/renderer/init.js
  src/talk/talk.window.js
Labels: bug, 3. to review

#742 fix(patchers): ignore unset baseURL in @nextcloud/router
  src/patchers/@nextcloud/router.js
Labels: bug, 3. to review

#737 fix(UserMenu): minor visual issues
  src/talk/renderer/assets/overrides.css
  src/talk/renderer/components/ThemeLogo.vue
  src/talk/renderer/components/UiMenuItem.vue
  src/talk/renderer/components/UserMenu.vue
Labels: bug, 3. to review

#747 fix: federation feature is always disabled
  src/shared/setupWebPage.js
Labels: bug, 3. to review

#746 fix: make Talk window more compact to fit into full HD
  src/talk/talk.window.js
Labels: bug, 3. to review

#752 chore(ci): add reuse check and fix reuse
  .editorconfig
  .github/workflows/reuse.yml
  .reuse/dep5
  LICENSES/CC-BY-SA-3.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/LicenseRef-AppleAppStoreBadge.txt
  LICENSES/LicenseRef-CollaboraTrademarks.txt
  LICENSES/LicenseRef-FacebookTrademarks.txt
  LICENSES/LicenseRef-GooglePlayBadge.txt
  LICENSES/LicenseRef-MastodonTrademarks.txt
  LICENSES/LicenseRef-XTrademarks.txt
  REUSE.toml
  resources/server-global-styles/master/.reuse/dep5
  resources/server-global-styles/master/REUSE.toml
  resources/server-global-styles/stable30/.reuse/dep5
  resources/server-global-styles/stable30/REUSE.toml
  scripts/fetch-server-styles.mjs
  scripts/utils/reuse.utils.mjs
Labels: 3. to review, technical debt

#754 fix(help): adjust paddings and elements size
  src/help/renderer/HelpApp.vue
Labels: bug, 3. to review

#756 release: v0.35.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#761 fix(talk): set --header-height
  src/shared/setupWebPage.js
  src/talk/renderer/init.js
Labels: bug, 3. to review

#766 fix: handle system theme change
  .gitattributes
  resources/server-global-styles/master/REUSE.toml
  resources/server-global-styles/master/apps/theming/theme/dark.plain.css
  resources/server-global-styles/master/apps/theming/theme/light.plain.css
  resources/server-global-styles/master/core/css/server.css
  resources/server-global-styles/stable30/REUSE.toml
  resources/server-global-styles/stable30/apps/theming/theme/dark.plain.css
  resources/server-global-styles/stable30/apps/theming/theme/light.plain.css
  resources/server-global-styles/stable30/core/css/server.css
  scripts/fetch-server-styles.mjs
  scripts/utils/reuse.utils.mjs
  src/shared/assets/global.styles.css
  src/shared/theme.utils.js
Labels: bug, 3. to review

#774 refactor: remove --header-height set on .content
  src/talk/renderer/assets/overrides.css
Labels: 3. to review, technical debt

#773 fix(UserMenu): reset default button color style
  src/talk/renderer/components/UiMenuItem.vue
Labels: bug, 3. to review

#777 fix(resources): broken with incorrect gitattributes for eol
  .gitattributes
  img/icons/icon-tray-linux.png
  img/icons/icon-tray-mac-dark.png
  img/icons/icon-tray-mac-dark@2x.png
  img/icons/icon-tray-mac-light.png
  img/icons/icon-tray-mac-light@2x.png
  img/icons/icon-tray-mac.png
  img/icons/icon-tray-mac@2x.png
  img/icons/icon.icns
  img/icons/icon.png
  resources/vue-devtools.crx
  sounds/notification.ogg
  sounds/talk.ogg
Labels: bug, 3. to review

#765 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated
