Repository nextcloud/talk-desktop, pull requests merged in 2024-07, with the labels that each got.

#710 Release v0.32.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#714 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#716 refactor: migrate to Composition API with SFC Setup and new defaults
  .eslintrc.js
  src/authentication/renderer/AuthenticationApp.vue
  src/help/renderer/HelpApp.vue
  src/shared/globals/OC/OcDialogsAdapter.vue
  src/shared/setupWebPage.js
  src/talk/renderer/DesktopHeader.vue
  src/talk/renderer/UserStatus/userStatus.service.js
  src/talk/renderer/Viewer/ViewerApp.vue
  src/talk/renderer/Viewer/ViewerHandlerImages.vue
  src/talk/renderer/Viewer/ViewerHandlerVideos.vue
  src/talk/renderer/components/UiMenu.vue
  src/talk/renderer/components/UiMenuItem.vue
  src/talk/renderer/components/UiMenuSeparator.vue
  src/upgrade/renderer/UpgradeApp.vue
Labels: 3. to review, technical debt

#717 fix(authentication): create a new cache partition on open login web-view
  src/authentication/login.window.js
Labels: bug, 3. to review
