Repository nextcloud/talk-desktop, pull requests merged in 2024-03, with the labels that each got.

#542 fix(talk): support Pinia talkHashStore for Talk 19
  forge.config.js
  src/talk/renderer/init.js
  src/talk/renderer/talk.main.js
Labels: bug, 3. to review

#547 release: v0.22.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: technical debt

#550 fix(talk): correctly import Vuex store from Talk
  src/talk/renderer/init.js
Labels: bug, 3. to review

#551 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
Labels: 3. to review, dependencies, automated

#556 build: support TS in Talk
  package-lock.json
  package.json
  tsconfig.json
  webpack.renderer.config.js
Labels: 3. to review

#557 chore(deps): pin undici on 6.6.2
  package-lock.json
  package.json
Labels: 3. to review

#559 release: v0.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#561 release: v0.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#567 fix(talk): support original path for root page
  src/talk/renderer/talk.main.js
Labels: 3. to review

#570 chore(release): Bump version to 0.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#571 fix(docs): Improve release docs
  README.md
Labels: 3. to review

#582 Release v0.26.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
