Repository nextcloud/talk-desktop, pull requests merged in 2024-02, with the labels that each got.

#506 release: v0.21.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#516 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
Labels: 3. to review, dependencies, automated

#308 fix: window icons on linux
  src/authentication/authentication.window.js
  src/authentication/login.window.js
  src/help/help.window.js
  src/shared/icons.utils.js
  src/talk/talk.window.js
  src/upgrade/upgrade.window.js
  src/welcome/welcome.window.js
Labels: bug, 3. to review, os: Linux 🐧

#540 fix: "Share from Nextcloud" support
  README.md
  src/app/webRequestInterceptor.js
  src/patchers/@nextcloud/axios.js
  src/patchers/@nextcloud/initial-state.js
Labels: bug, 3. to review
