Repository nextcloud/talk-desktop, pull requests merged in 2024-10, with the labels that each got.

#827 chore(devDeps): bump electron to 32.2.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#828 chore(deps): update minor dev deps
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#829 chore(deps): bump vue-material-design-icons to 5.3.1
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#830 release: v0.39.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#831 fix(Viewer): expose Viewer.mimetypes as unified array of supported mimes
  src/talk/renderer/Viewer/Viewer.js
Labels: enhancement, 3. to review

#837 fix(viewer): handle viewer close
  src/talk/renderer/Viewer/ViewerApp.vue
Labels: bug, 3. to review

#835 feat: add application config aka settings
  .eslintrc.js
  src/app/AppConfig.ts
  src/authentication/authentication.window.js
  src/main.js
  src/preload.js
  src/shared/appConfig.service.ts
  src/shared/setupWebPage.js
  src/talk/renderer/Settings/DesktopSettingsSection.vue
  src/talk/renderer/Settings/appConfig.store.ts
  src/talk/renderer/Settings/components/SettingsSelect.vue
  src/talk/renderer/Settings/components/SettingsSubsection.vue
  src/talk/renderer/Settings/index.ts
  src/talk/renderer/Settings/useAppConfigValue.ts
  src/talk/renderer/components/MainMenu.vue
  src/talk/renderer/composables/useNcSelectModel.ts
  src/talk/renderer/talk.main.js
  src/talk/renderer/utils/createCustomElement.ts
  src/talk/talk.window.js
  src/welcome/welcome.window.js
  tsconfig.json
  webpack.main.config.js
Labels: enhancement, 3. to review

#836 feat: monochrome tray icon
  img/icons/icon-tray-mac.png
  img/icons/icon-tray-mac@2x.png
  img/icons/icon-tray-win32-dark.ico
  img/icons/icon-tray-win32-light.ico
  scripts/generate-icons.js
  src/app/AppConfig.ts
  src/shared/icons.utils.js
  src/shared/os.utils.js
  src/talk/renderer/Settings/DesktopSettingsSection.vue
  src/talk/renderer/Settings/appConfig.store.ts
  src/talk/talk.window.js
Labels: bug, enhancement, 3. to review

#840 feat: handle download links
  src/app/applyDownloadNotification.js
  src/app/downloads.ts
  src/app/externalLinkHandlers.js
  src/main.js
  src/preload.js
  src/shared/setupWebPage.js
  src/talk/talk.window.js
Labels: enhancement, 3. to review

#846 build: rename scripts `package` to `build`, `make` to `package`
  README.md
  package.json
  scripts/prepare-release-packages.mjs
Labels: 3. to review, technical debt

#847 fix(build): check whether spreed repository are installed in generateAssets() hook
  forge.config.js
Labels: bug, 3. to review

#852 fix(app): show window on activate on macOS
  src/main.js
Labels: bug, 3. to review, os: Mac 🍎

#853 feat: add zoom config on UI and fix zoom-related issues
  src/app/AppConfig.ts
  src/app/app.menu.js
  src/app/applyWheelZoom.js
  src/app/utils.ts
  src/app/zoom.service.ts
  src/authentication/authentication.window.js
  src/authentication/login.window.js
  src/constants.js
  src/help/help.window.js
  src/preload.js
  src/shared/appConfig.service.ts
  src/talk/renderer/Settings/DesktopSettingsSection.vue
  src/talk/renderer/Settings/appConfig.store.ts
  src/talk/renderer/Settings/components/SettingsFormGroup.vue
  src/talk/renderer/Settings/components/SettingsSelect.vue
  src/talk/renderer/Settings/useAppConfigValue.ts
  src/talk/talk.window.js
  src/upgrade/upgrade.window.js
  src/welcome/welcome.window.js
Labels: enhancement, 3. to review

#841 build: add Squirrel.Windows
  REUSE.toml
  forge.config.js
  img/squirrel-install-loading.gif
  package-lock.json
  package.json
  src/main.js
Labels: enhancement, 3. to review

#854 fix(notifications): remove notification (talk) icon from notification image
  src/talk/renderer/notifications/notifications.store.js
Labels: bug, 3. to review
