Repository nextcloud/talk-desktop, pull requests merged in 2024-01, with the labels that each got.

#468 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#477 release: v0.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#488 chore(dev): change default Webpack logger port from 9000 for 9005
  forge.config.js
Labels: 3. to review, technical debt

#489 Update npm and node engines versions
  package.json
Labels: dependencies
