Repository nextcloud/talk-desktop, pull requests merged in 2024-04, with the labels that each got.

#593 chore(deps): pin exact undici@6.6.2
  package-lock.json
  package.json
Labels: dependencies

#598 build: drop support for building with Talk v17
  src/constants.js
  webpack.renderer.config.js
Labels: technical debt

#595 feat: screen sharing
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/main.js
  src/preload.js
  src/shared/os.utils.js
  src/talk/renderer/AppGetDesktopMediaSource.vue
  src/talk/renderer/components/DesktopMediaSourceDialog.vue
  src/talk/renderer/components/DesktopMediaSourcePreview.vue
  src/talk/renderer/getDesktopMediaSource.js
  src/talk/renderer/talk.main.js
Labels: enhancement, 3. to review

#322 feat: Image Viewer
  README.md
  src/talk/renderer/Viewer/Viewer.js
  src/talk/renderer/Viewer/ViewerApp.vue
  src/talk/renderer/Viewer/ViewerHandlerImages.vue
  src/talk/renderer/Viewer/ViewerHandlerVideos.vue
  src/talk/renderer/talk.main.js
Labels: enhancement, 3. to review

#603 fix(patchers): patch router without permanent absolute _oc_webroot
  package-lock.json
  package.json
  src/patchers/@nextcloud/router.js
  src/shared/globals/globals.js
  src/talk/renderer/talk.main.js
Labels: bug, 3. to review

#606 fix: prettify links by using actual modRewriteWorking from capabilities for Nextcloud 29+
  src/shared/globals/globals.js
Labels: bug, 3. to review

#604 release: v0.28.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: technical debt

#618 fix(screensharing): better sort and name available sources
  src/talk/renderer/components/DesktopMediaSourceDialog.vue
  src/talk/renderer/components/DesktopMediaSourcePreview.vue
Labels: bug, 3. to review, design

#619 fix: show mime type icon for attachments in messages
  src/shared/globals/OC/mimetype.js
  src/shared/globals/globals.js
Labels: bug, 3. to review

#620 feat: workaround for multi-account support with several instance with different executable names
  README.md
  src/main.js
  src/preload.js
  src/shared/setupWebPage.js
Labels: enhancement, 3. to review

#617 feat: new title bar design
  src/authentication/authentication.window.js
  src/authentication/renderer/AuthenticationApp.vue
  src/talk/renderer/DesktopHeader.vue
  src/talk/renderer/Viewer/ViewerApp.vue
  src/talk/renderer/assets/overrides.css
  src/talk/renderer/components/UserMenu.vue
  src/talk/renderer/desktop.app.js
  src/talk/renderer/init.js
  src/talk/renderer/talk.main.js
  src/talk/talk.window.js
  src/welcome/welcome.window.js
Labels: enhancement, 3. to review, design

#623 fix: show main window after login
  src/main.js
Labels: bug, 3. to review

#624 release: v0.29.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#636 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
