Repository nextcloud/talk-desktop, pull requests merged in 2025-07, with the labels that each got.

#1358 fix(linux/flatpak): second instance detection
  src/app/system.utils.ts
  src/main.js
Labels: bug, 3. to review, os: Linux 🐧

#1356 feat: add Quit button to the user menu
  src/talk/renderer/TitleBar/TitleBar.vue
  src/talk/renderer/TitleBar/components/UserMenu.vue
Labels: enhancement, 3. to review, backport-request

#1363 fix(title-bar): open in web link is broken
  src/talk/renderer/TalkWrapper/talk.service.ts
Labels: bug, 3. to review, regression

#1365 [stable1] build: update built-in Talk versions
  package.json
Labels: 3. to review, distribution 📦

#1366 build: update built-in Talk versions
  package.json
Labels: 3. to review, distribution 📦

#1370 chore(l10n): add stable1 to backports
  .tx/backport
  REUSE.toml
Labels: 3. to review, technical debt

#1371 chore: cherry pick missing translations
  l10n/de.js
  l10n/de.json
  l10n/id.js
  l10n/id.json
  l10n/tr.js
  l10n/tr.json
Labels: 3. to review, technical debt

#1369 release: v1.2.4
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1375 fix(app): window title is untranslated and may duplicate on reload
  src/authentication/authentication.window.js
  src/authentication/login.window.js
  src/authentication/renderer/authentication.main.js
  src/certificate/certificate.window.ts
  src/certificate/renderer/certificate.main.ts
  src/help/help.window.js
  src/help/renderer/help.app.js
  src/main.js
  src/preload.js
  src/shared/setupWebPage.js
  src/upgrade/renderer/upgrade.main.ts
  src/upgrade/upgrade.window.ts
Labels: bug, 3. to review, backport-request

#1355 fix: use outline icons
  src/callbox/renderer/CallboxApp.vue
  src/talk/renderer/TitleBar/components/MainMenu.vue
  src/talk/renderer/TitleBar/components/UserMenu.vue
  src/upgrade/renderer/UpgradeApp.vue
Labels: 3. to review, design

#1378 fix(title-bar): logout and quit buttons do not work
  src/talk/renderer/TitleBar/components/UserMenu.vue
Labels: bug, 3. to review, regression

#1380 fix: get app version for initial state from app data
  src/shared/setupWebPage.js
Labels: bug, 3. to review

#1383 chore(ci/dependabot): include stable1
  .github/dependabot.yml
Labels: 3. to review, technical debt

#1382 [stable1] chore(deps): update deps, including electron ^36.5.0 → ^37.2.3
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1385 chore(release): add v1.2.5 changelog
  CHANGELOG.md
Labels: 3. to review, technical debt
