Repository nextcloud/talk-desktop, pull requests merged in 2025-05, with the labels that each got.

#1261 fix(app): rework networking to serve app over `https://<server_url>` origin instead of `nctalk://` or `file://`
  eslint.config.mjs
  forge.config.js
  package-lock.json
  package.json
  src/app/appData.service.js
  src/app/appProtocol.ts
  src/app/applyContextMenu.js
  src/app/externalLinkHandlers.ts
  src/app/utils.ts
  src/app/webRequestInterceptor.js
  src/authentication/authentication.window.js
  src/authentication/renderer/AuthenticationApp.vue
  src/callbox/callbox.window.ts
  src/constants.js
  src/global.d.ts
  src/help/help.window.js
  src/main.js
  src/patchers/@nextcloud/router.js
  src/preload.js
  src/reset.d.ts
  src/shared/globals/globals.js
  src/shared/ocs.service.js
  src/shared/setupWebPage.js
  src/talk/talk.window.js
  src/upgrade/upgrade.window.ts
  src/welcome/welcome.window.js
  webpack.renderer.config.js
Labels: bug, 3. to review

#1283 chore: migrate to Electron 36 `session.extensions`
  src/install-vue-devtools.js
Labels: 3. to review, technical debt

#1285 release: v1.1.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1284 chore: update pull_request_template.md
  .github/pull_request_template.md
Labels: 3. to review, technical debt

#1287 release: v1.2.0-beta
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1290 fix(linux): crash with GTK version error on GNOME
  src/main.js
Labels: bug, 3. to review, os: Linux 🐧

#1295 release: v1.2.1-beta
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1299 fix(title-bar): remove logo click in favor of new home button
  src/talk/renderer/TitleBar/TitleBar.vue
Labels: bug, 3. to review

#1312 fix(app): always re-fetch capabilities and user data on launch
  src/app/appData.service.js
  src/welcome/welcome.js
Labels: bug, 3. to review

#1315 chore(deps): bump @nextcloud/vue from 8.26.1 to 8.27.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies
