Repository nextcloud/talk-desktop, pull requests merged in 2025-02, with the labels that each got.

#1083 fix(upgrade): adjust styles
  forge.config.js
  src/main.js
  src/upgrade/renderer/UpgradeApp.vue
  src/upgrade/renderer/upgrade.main.ts
  src/upgrade/upgrade.window.ts
Labels: bug, 3. to review, design

#1106 chore(deps): update
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1104 feat(notifications): play call notification sound on second output device
  src/app/AppConfig.ts
  src/talk/renderer/Settings/DesktopSettingsSection.vue
  src/talk/renderer/Settings/components/SettingsFormGroup.vue
  src/talk/renderer/Settings/components/SettingsSelect.vue
  src/talk/renderer/composables/useNcSelectModel.ts
  src/talk/renderer/notifications/notifications.store.js
Labels: enhancement, 3. to review

#1107 chore: remove moment
  package-lock.json
  package.json
  src/shared/datetime.utils.ts
  src/talk/renderer/UserStatus/components/UserStatusFormClearAt.vue
  src/talk/renderer/UserStatus/userStatus.utils.ts
Labels: 3. to review, dependencies, technical debt

#1103 build: windows .msi via WiX
  README.md
  REUSE.toml
  forge.config.js
  img/wix-background.bmp
  img/wix-banner.bmp
  package-lock.json
  package.json
  scripts/wix-background-generator.html
  src/main.js
Labels: 3. to review, distribution 📦

#1120 release: v1.1.4 beta
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1121 fix: set circles_enabled in initial state from server capabilities
  src/shared/setupWebPage.js
Labels: bug, 3. to review

#1123 fix(callbox): loop ringtone
  package-lock.json
  package.json
  src/callbox/callbox.window.ts
  src/callbox/renderer/CallboxApp.vue
  src/callbox/renderer/callbox.utils.ts
  src/talk/renderer/TitleBar/components/DevMenu.vue
  src/talk/renderer/notifications/notifications.store.js
Labels: bug, 3. to review

#1136 fix(user-status): emoji picker cannot be focused
  src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue
Labels: bug, 3. to review

#1139 release: v1.1.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt
