Repository nextcloud/talk-desktop, pull requests merged in 2025-09, with the labels that each got.

#1445 build: update built-in Talk versions
  package.json
Labels: 3. to review, distribution 📦

#1444 chore(ts): fix error in getDesktopMediaSource.ts
  src/talk/renderer/screensharing/getDesktopMediaSource.ts
Labels: 3. to review, backport-request, technical debt

#1453 release: v2.0.0-beta
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1480 build: update built-in Talk versions
  package.json
Labels: 3. to review, distribution 📦

#1478 fix(app): support network streams
  src/app/appProtocol.ts
Labels: bug, 3. to review

#1482 release: v2.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt
