Repository nextcloud/talk-desktop, pull requests merged in 2025-08, with the labels that each got.

#1413 build: update built-in Talk versions
  package.json
Labels: 3. to review, technical debt

#1424 chore: update dependencies
  package-lock.json
  package.json
  src/authentication/renderer/AuthenticationApp.vue
  src/talk/renderer/TitleBar/components/DevMenu.vue
  src/talk/renderer/TitleBar/components/MainMenu.vue
  src/talk/renderer/Viewer/ViewerHandlerBase.vue
  src/talk/renderer/screensharing/DesktopMediaSourceDialog.vue
Labels: 3. to review, dependencies, technical debt

#1425 build: update node and npm engines versions
  package.json
Labels: dependencies

#1432 chore(deps): bump nextcloud/vue library to v9.0.0-rc.7
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1433 feat(user_status): add 'Busy' status support
  src/talk/renderer/TitleBar/components/UserMenu.vue
  src/talk/renderer/UserStatus/userStatus.utils.ts
Labels: enhancement, 3. to review

#1434 chore(deps): update vue from 3.5.19 to 3.5.20
  package-lock.json
  package.json
Labels: bug, 3. to review, dependencies
