Repository nextcloud/talk-desktop, pull requests merged in 2025-04, with the labels that each got.

#1201 chore: migrate to `@nextcloud/vue@8.24.0`
  src/authentication/renderer/AuthenticationApp.vue
  src/callbox/renderer/CallboxApp.vue
  src/help/renderer/HelpApp.vue
  src/talk/renderer/Settings/DesktopSettingsSection.vue
  src/talk/renderer/UserStatus/components/UserStatusForm.vue
  src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue
  src/talk/renderer/UserStatus/components/UserStatusFormPredefinedOption.vue
  src/talk/renderer/UserStatus/components/UserStatusFormStatusType.vue
  src/talk/renderer/Viewer/ViewerHandlerText.vue
  src/upgrade/renderer/UpgradeApp.vue
Labels: 3. to review, technical debt

#1193 chore: build config
  REUSE.toml
  build/BuildConfig.types.ts
  build/config.json
  build/resolveBuildConfig.js
  eslint.config.mjs
  forge.config.js
  img/server-logo-plain.svg
  package.json
  src/app/app.menu.js
  src/app/utils.ts
  src/authentication/renderer/AuthenticationApp.vue
  src/global.d.ts
  src/help/renderer/HelpApp.vue
  src/main.js
  src/preload.js
  src/shared/build.config.ts
  src/talk/renderer/TitleBar/TitleBar.vue
  src/talk/renderer/TitleBar/components/MainMenu.vue
  src/welcome/welcome.html
  tsconfig.json
  webpack.main.config.js
  webpack.renderer.config.js
Labels: 3. to review

#1204 chore: add internal app protocol
  eslint.config.mjs
  forge.config.js
  src/app/appProtocol.ts
  src/app/externalLinkHandlers.ts
  src/app/utils.ts
  src/app/webRequestInterceptor.js
  src/authentication/authentication.window.js
  src/callbox/callbox.window.ts
  src/constants.js
  src/global.d.ts
  src/help/help.window.js
  src/main.js
  src/talk/renderer/talk.main.ts
  src/talk/talk.window.js
  src/upgrade/upgrade.window.ts
  src/welcome/welcome.window.js
Labels: 3. to review

#1224 build(talk): bump built-in Talk to v21.0.3
  package.json
Labels: 3. to review, distribution 📦

#1223 chore(deps): bump @nextcloud/vue to 8.25.1
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1200 Add custom showCertificateTrustDialog for Linux
  src/app/AppConfig.ts
  src/main.js
Labels: enhancement, 3. to review

#1225 release: v1.1.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1237 perf(user-status): do not request backup status until user status form open
  src/talk/renderer/TitleBar/components/UserMenu.vue
  src/talk/renderer/UserStatus/UserStatusDialog.vue
  src/talk/renderer/UserStatus/components/UserStatusForm.vue
  src/talk/renderer/UserStatus/components/UserStatusFormBackup.vue
  src/talk/renderer/UserStatus/components/UserStatusFormCustomMessage.vue
  src/talk/renderer/UserStatus/components/UserStatusFormPredefinedOption.vue
  src/talk/renderer/UserStatus/predefinedStatuses.store.ts
  src/talk/renderer/UserStatus/userStatus.store.ts
Labels: bug, 3. to review, performance 🚀

#1236 fix: avoid preflight (OPTIONS) request by using internal reverse proxy
  src/app/appProtocol.ts
  src/app/webRequestInterceptor.js
  src/authentication/renderer/AuthenticationApp.vue
  src/main.js
  src/shared/setupWebPage.js
  src/welcome/welcome.js
Labels: bug, 2. developing, performance 🚀, regression

#1235 fix(app): errors due to incorrect language format
  src/main.js
  src/shared/setupWebPage.js
Labels: bug, 3. to review

#1250 build: use dot in sanitized dist name
  forge.config.js
Labels: bug, 3. to review, distribution 📦

#1247 chore(README): add `choco`
  README.md
Labels: 3. to review, distribution 📦

#1254 fix: adjust mimetype icon for directories
  src/shared/globals/OC/mimetype.js
Labels: bug, 3. to review
