Repository nextcloud/talk-desktop, pull requests merged in 2025-03, with the labels that each got.

#1153 fix(talk): remove escape hotkey as it's added in Talk
  src/talk/renderer/TalkDesktop.vue
Labels: 3. to review

#1164 fix: substitute empty locale from server with system locale
  src/shared/setupWebPage.js
Labels: bug, 3. to review

#1154 chore(windows/msi): update logo in installer background
  REUSE.toml
  img/talk-logo-spaced.svg
  img/talk-logo.svg
  img/wix-background.bmp
  scripts/wix-background-generator.html
Labels: 3. to review, design
